version: '3.9'

services:
    traefik:
        image: traefik:v2.4
        container_name: "traefik"
        networks:
            proxy:
        command: --api.insecure=true --providers.docker --web --docker --logLevel=DEBUG
        ports:
            # The HTTP port
            - "80:80"
            - "443:443"
            # The Web UI (enabled by --api.insecure=true)
            - "8070:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./config/traefik.toml:/traefik.toml
            - ./config/acme.json:/acme.json
        labels:
            - "traefik.enable=true" # enables the service
            - "traefik.http.routers.traefik.rule=Host(`traefik.local`)" # domain to expose on
            - "traefik.docker.network=traefik_proxy"
        restart: unless-stopped
networks:
    proxy:
        driver: bridge
        name: traefik_proxy
