http:
  routers:
    traefik:
      rule: "Host(`traefik.local`)"
      service: "api@internal"

tls:
  certificates:
    - certFile: "/etc/certs/local.pem"
      keyFile: "/etc/certs/local-key.pem"
